name: develop ci

on:
  push:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: cd DcsBiosReader && dotnet publish -c Release --manifest plugin_manifest.xml -p:DebugType=None -o publish/DcsBiosReader
    - name: Zip Folder
      run: cd DcsBiosReader/publish && zip -r DcsBiosReader.zip .
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "alpha"
        files: |
            **/DcsBiosReader.zip
